.github/pull_request_template.md
:어깨를_으쓱하는_남성: -> :man_shrugging:
깃허브에서는 한글로 된 이모지를 지원하지 않습니다.  
따라서 잘못된 이모지 사용법을 수정하였습니다.
=> [fix] 한글로 된 이모지 수정

.github/workflows/lint_and_build.yml
- github secrets를 이용하여 google-service.json 파일 생성
=> [chore] CI에서 `google-service.json`이 존재하지 않는 문제 해결

app/src/main/java/com/boostcamp/dreamteam/dreamdiary/navigation/DreamDiaryNavHost.kt, feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/home/DiaryHomeNavigatioin.kt, feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/home/DiaryHomeScreen.kt, feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/home/DiaryHomeUIState.kt, feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/home/DiaryHomeViewModel.kt, feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/home/components/DiaryCard.kt, feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/home/components/DiaryListTab.kt, feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/models/DiaryUi.kt, feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/models/LabelUi.kt, feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/models/vos/DisplayableDateTime.kt
=> [refactor] domain model과 ui model 분리

core/data/schemas/com.boostcamp.dreamteam.dreamdiary.core.data.database.DreamDiaryDatabase/1.json, core/data/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/data/database/DreamDiaryDatabase.kt, core/data/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/data/database/dao/DreamDiaryDao.kt, core/data/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/data/database/model/LabelEntity.kt, core/data/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/data/repository/DefaultDreamDiaryRepository.kt, core/data/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/data/repository/DreamDiaryRepository.kt, core/domain/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/domain/usecase/AddLabelUseCase.kt
#51 
room database에 라벨 entity 추가
라벨을 추가할 수 있는 repository 함수 및 usecase 함수 생성
=> [feat] 라벨 추가

core/model/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/model/Label.kt, feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/home/components/DiaryCalendar.kt, feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/home/components/DiaryCalendarBody.kt, feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/home/components/DiaryCalendarTab.kt, feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/home/components/DiaryCalendarYearMonthPicker.kt, feature/diary/src/main/res/values/strings.xml
close #53
- 오늘 날짜를 표시
- 오늘로 이동하는
- 년, 월을 선택하기 위한 다이얼로그
- 이전, 이후 월로 이동 가능한 버튼
<p align="center">
<img
src="https://github.com/user-attachments/assets/c07984df-2b97-429c-add5-73065480beb6"
width="30%"
/>
<img
src="https://github.com/user-attachments/assets/d60a9ee5-aa17-4b39-965b-75d6ee06d275"
width="30%"
/>
<img
src="https://github.com/user-attachments/assets/2fb0feff-3eb0-4916-8700-39bfcb05cc03"
width="30%"
/>
</p>
=> [feat] 날짜만 표시되는 달력 구현

feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/home/DiaryHomeScreen.kt, feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/home/DiaryHomeViewModel.kt, feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/home/components/DiaryCard.kt, feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/home/tabcalendar/DiaryCalendarTab.kt, feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/home/tablist/DiaryHomeTabListUIState.kt, feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/home/tablist/DiaryHomeUIState.kt, feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/home/tablist/DiaryListTab.kt, feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/models/DiaryUi.kt
=> [refactor] tab별 uistate 클래스 분리

core/data/schemas/com.boostcamp.dreamteam.dreamdiary.core.data.database.DreamDiaryDatabase/1.json, core/data/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/data/database/DreamDiaryDatabase.kt, core/data/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/data/database/dao/DreamDiaryDao.kt, core/data/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/data/database/model/DreamDiaryLabelEntity.kt, core/data/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/data/repository/DefaultDreamDiaryRepository.kt, core/data/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/data/repository/DreamDiaryRepository.kt, core/domain/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/domain/usecase/AddDreamDiaryUseCase.kt, feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/write/DiaryWriteViewModel.kt
#73 
꿈일기를 저장할 때 체크해 둔 라벨을 함께 저장합니다.
- 꿈일기와 라벨의 관계를 나타내는 n:n 엔티티를 생성했습니다.
=> [feat] 꿈일기를 저장할 때 라벨을 함께 저장할 수 있는 기능

feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/home/DiaryHomeScreen.kt, feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/home/component/DiaryCalendar.kt, feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/home/component/DiaryCalendarBody.kt, feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/home/component/DiaryCalendarBottomSheet.kt, feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/home/tabcalendar/DiaryCalendarTab.kt, feature/diary/src/main/res/values/strings.xml
Added calendar bottom sheet functionality to display diary entries for selected dates. The bottom sheet includes:
- Empty state UI when no diary entries exist for the selected date
- List view of diary entries showing title, date, and content preview
- Navigation buttons to move between days
- Click handling on calendar days to show the bottom sheet
- Localized strings for navigation and empty states
The calendar component now supports day selection and maintains the selected date state, enabling users to browse through their diary entries chronologically.
=> [feat] bottom sheet에 일기 목록 표시

feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/model/LabelUi.kt, feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/write/DiaryWriteScreen.kt, feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/write/DiaryWriteViewModel.kt, feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/write/component/DiaryWriteScreenHeader.kt, feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/write/component/LabelSelectionDialog.kt, feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/write/model/DiaryWriteUiState.kt, feature/diary/src/main/res/values/strings.xml
라벨을 검색할 때 라벨이 사라지면 체크 정보도 사라지는 문제점을 해결했습니다.
uiState 가져올 때 구조분해를 사용하지 않게 했습니다. 좀 읽기 어려워서요.
라벨을 검색할 때 사용하는 변수 searchValue와 onSearchValueChange의 이름을 labelFilter, onLabelFilterChange로 이름을 변경했습니다. 기존에는 이름이 애매했던 것 같아요.
selectableLabels로 관리하던 라벨을 filteredLabels와 selectedLabels 두 개로 관리하게 변경했습니다. filteredLabels는 검색어 labelFilter에 의해 필터링 된 라벨이고, selectedLabels는 필터와 상관 없이 선택된 라벨을 보관합니다.
=> [fix] 라벨 검색 시 버그 수정

app/build.gradle.kts, app/src/main/java/com/boostcamp/dreamteam/dreamdiary/navigation/DreamDiaryNavHost.kt, feature/setting/build.gradle.kts, feature/setting/src/main/java/com/boostcamp/dreamteam/dreamdiary/setting/SettingNavigation.kt, feature/setting/src/main/java/com/boostcamp/dreamteam/dreamdiary/setting/SettingScreen.kt
setting screen bottom bar와 연결했습니다.
이 부분의 코드가 중복되는데 어떻게 해결하는 것이 좋을까요?
```kt
val navigationItems = listOf(
NavigationItem(
icon = HomeBottomNavItem.MyDream.icon,
labelRes = HomeBottomNavItem.MyDream.label,
isSelected = true,
onClick = {  },
),
NavigationItem(
icon = HomeBottomNavItem.Community.icon,
labelRes = HomeBottomNavItem.Community.label,
isSelected = false,
onClick = onNavigateToCommunity,
),
NavigationItem(
icon = HomeBottomNavItem.Setting.icon,
labelRes = HomeBottomNavItem.Setting.label,
isSelected = false,
onClick = onNavigateToSetting,
),
)
```
=> [feat] setting screen을 bottom bar 연결

app/src/main/java/com/boostcamp/dreamteam/dreamdiary/navigation/DreamDiaryNavHost.kt, core/data/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/data/database/dao/DreamDiaryDao.kt, core/data/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/data/database/model/DreamDiaryWithLabels.kt, core/data/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/data/repository/DefaultDreamDiaryRepository.kt, core/data/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/data/repository/DreamDiaryRepository.kt, core/data/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/data/repository/Mapper.kt, core/domain/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/domain/usecase/GetDreamDiaryUseCase.kt, feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/detail/DiaryDetailNavigation.kt, feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/detail/DiaryDetailScreen.kt, feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/detail/DiaryDetailViewModel.kt, feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/detail/model/DiaryDetailUiState.kt, feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/home/DiaryHomeScreen.kt, feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/write/component/DiaryWriteScreenHeader.kt, feature/diary/src/main/res/values/strings.xml
#17 
꿈일기 상세 화면을 구현했습니다.
- 리스트에서 네비게이션
- 꿈일기와 관련 라벨을 한꺼번에 가져올 수 있는 유즈케이스 및 dao 함수
꿈일기 홈 화면에서 탭 인덱스를 savable에 보관하도록 변경했습니다. 상세 화면 갔다가 돌아왔을 때 유지가 되면 좋을 것 같아서요.
=> [feat] 꿈일기 상세 화면

feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/write/DiaryWriteScreen.kt
=> [fix] 작성 화면에서 스크롤 시 padding이 이상하게 적용되는 문제 해결

feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/component/DiaryMenuButton.kt, feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/home/component/DiaryCard.kt
-[x] 상세 화면에서도 사용하기 위해 `DiaryMenuButton` component 분리
=> [refactor] DiaryMenuButton 컴포넌트 분리

gradle.properties
`2.1`초나 걸리는 configuration 과정을 cache를 사용하면 건너뛸 수 있다고 합니다.
1. build는 3단계로 구성되어있음 (1. Initialization 2. Configuration 3. Execution)
2. Configuration과정이란 모든 build.gradle(.kts)와 properties를 모아 task 그래프를 그리며  빌드를 준비하는 과정
3. 캐시가 있으면 configuration 과정을 스킵함
https://docs.gradle.org/current/userguide/build_lifecycle.html#sec:configuration
https://docs.gradle.org/current/userguide/configuration_cache.html
=> [chore] configuration-cache를 사용하도록 설정

feature/community/src/main/java/com/boostcamp/dreamteam/dreamdiary/community/CommunityNavigation.kt, feature/community/src/main/java/com/boostcamp/dreamteam/dreamdiary/community/list/CommunityListScreen.kt, feature/community/src/main/java/com/boostcamp/dreamteam/dreamdiary/community/list/component/CommunityDiaryCard.kt, feature/community/src/main/java/com/boostcamp/dreamteam/dreamdiary/community/model/DiaryUi.kt, feature/community/src/main/java/com/boostcamp/dreamteam/dreamdiary/community/model/UserUi.kt, feature/community/src/main/java/com/boostcamp/dreamteam/dreamdiary/community/model/vo/DisplayableDateTime.kt, feature/community/src/main/java/com/boostcamp/dreamteam/dreamdiary/community/model/vo/DisplayableDateTimeFormatter.kt, feature/community/src/main/res/values/strings.xml
closes #187 
to. 디자이너님  
댓클 버튼이랑 좋아요 버튼 순서를 figma랑 다르게 했어요  
댓글 개수에 따라 버튼 위치가 움직이는게 화가 막 나더라구요
좋아요가 오른쪽에 가려면 차라리 오른쪽 정렬이 나은 듯?
=> [feat] 커뮤니티 일기 카드 구현

core/data/schema/com.boostcamp.dreamteam.dreamdiary.core.data.database.DreamDiaryDatabase/1.json, core/data/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/data/database/DreamDiaryDatabase.kt, core/data/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/data/database/dao/DreamDiaryDao.kt, core/data/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/data/database/model/SynchronizingLabelEntity.kt, core/data/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/data/firebase/functions/model/FunctionsSyncVersionRequest.kt, core/data/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/data/firebase/functions/model/FunctionsSynchronizeDiaryRequest.kt, core/data/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/data/repository/FunctionRepository.kt, core/model/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/model/synchronization/SynchronizeDreamDiaryRequest.kt, core/model/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/model/synchronization/SynchronizeDreamDiaryResponse.kt, core/synchronization/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/synchronization/Mapper.kt, core/synchronization/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/synchronization/SynchronizationWorker.kt
Content(텍스트 내용, 이미지 path 및 이미지 데이터)를 제외하고 서버와 동기화 합니다.
앞서 versionCheck를 통해 서버가 알려준 동기화 해야 하는 꿈일기 및 클라이언트에서 수정된 꿈일기를 서버에게 전송합니다.
Content가 없는 꿈일기는 아직 동기화가 끝나지 않았으므로, synchronizing_diary 테이블에 계속 보관합니다.
=> [feat] 동기화 functions needSync와의 로직

core/data/schema/com.boostcamp.dreamteam.dreamdiary.core.data.database.DreamDiaryDatabase/1.json, core/data/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/data/database/DreamDiaryDatabase.kt, core/data/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/data/database/dao/DreamDiaryDao.kt, core/data/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/data/database/model/SynchronizingContentEntity.kt, core/data/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/data/firebase/functions/model/FunctionsUploadImageContentRequest.kt, core/data/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/data/firebase/functions/model/FunctionsUploadTextContentRequest.kt, core/data/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/data/repository/FunctionRepository.kt, core/synchronization/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/synchronization/SynchronizationWorker.kt, feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/component/DiaryContentEditor.kt, feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/detail/DiaryDetailScreen.kt, feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/home/component/DiaryCard.kt, feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/write/DiaryWriteScreen.kt
업로드 해야 하는 꿈일기의 컨텐트(텍스트 내용, 이미지 데이터)를 찾고 이를 업로드합니다.
업로드 해야 하는 컨텐트를 보관하는 새로운 엔티티 SynchronizingContentEntity를 생성했습니다.
needSync(#201)의 호출 전, SynchronizingContentEntity에 업로드 해야 하는 컨텐트를 먼저 보관합니다.
기존에 이미지를 룸 DB에 저장할 때 full path를 함께 저장했으나, 파일 이름만 저장하고 path를 사용하는 쪽에서 `Context.filesDir`를 붙이게 변경하였습니다.
=> [feat] functions uploadText, uploadImage와의 로직 추가

core/data/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/data/database/dao/DreamDiaryDao.kt, core/data/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/data/database/model/SynchronizingDreamDiaryEntity.kt, core/data/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/data/firebase/functions/model/FunctionsDownloadImageContentRequest.kt, core/data/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/data/firebase/functions/model/FunctionsDownloadTextContentRequest.kt, core/data/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/data/repository/FunctionRepository.kt, core/model/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/model/synchronization/DownloadImageResponse.kt, core/model/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/model/synchronization/DownloadTextResponse.kt, core/synchronization/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/synchronization/NotDownloadedContent.kt, core/synchronization/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/synchronization/SynchronizationWorker.kt
서버에만 있는 컨텐트(텍스트, 이미지)를 받아오는 함수입니다. downloadImage는 이미지의 아이디와 path만 가지고 있으며, storage에서 해당 path로 재차 이미지를 받아옵니다.
로그아웃 및 다른 아이디로 로그인을 했을 때 동기화 관련 테이블을 비웁니다.
=> [feat] functions dowloadImage, downloadText와의 로직

app/src/main/java/com/boostcamp/dreamteam/dreamdiary/DreamDiaryApplication.kt, app/src/main/java/com/boostcamp/dreamteam/dreamdiary/MainActivity.kt
<details>
<summary>에러 전문</summary>
```text
java.lang.RuntimeException: Unable to create application com.boostcamp.dreamteam.dreamdiary.DreamDiaryApplication: android.app.ForegroundServiceStartNotAllowedException: startForegroundService() not allowed due to mAllowStartForeground false: service com.boostcamp.dreamteam.dreamdiary/.notification.ScreenTrackingService
at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7510)
at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2416)
at android.os.Handler.dispatchMessage(Handler.java:107)
at android.os.Looper.loopOnce(Looper.java:232)
at android.os.Looper.loop(Looper.java:317)
at …
```
=> [fix] `ForegroundServiceStartNotAllowedException`이 발생하는 문제 해결

feature/community/src/main/java/com/boostcamp/dreamteam/dreamdiary/community/detail/CommunityDetailScreen.kt
이전의 입력창이 너무 큰 것 같아 줄였습니다. 디자인은 유튜브의 댓글 입력창을 참고했습니다.
=> [feat] 신규 댓글 입력창 크기 줄이기

core/data/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/data/firebase/firestore/model/FirestoreAddCommunityPostRequest.kt, core/data/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/data/repository/CommunityRepository.kt
```
@Serializable
data class FirestoreAddCommunityPostRequest(
val id: String,
val uid: String,
val author: String,
val profileImageUrl: String,
val title: String,
val content: String,
val likeCount: Int,
val commentCount: Long,
@Transient
val createdAt: FieldValue = FieldValue.serverTimestamp(),
)
```
이렇게 해보는 것은 어떨까요?
수정을 제안해봅니다.
=> [fix] server timestamp를 map으로 추가하지 않게 변경

app/build.gradle.kts, app/src/main/java/com/boostcamp/dreamteam/dreamdiary/MainActivity.kt, app/src/main/java/com/boostcamp/dreamteam/dreamdiary/MainUiState.kt, app/src/main/java/com/boostcamp/dreamteam/dreamdiary/MainViewModel.kt, app/src/main/java/com/boostcamp/dreamteam/dreamdiary/ui/DreamDiaryApp.kt, core/data/build.gradle.kts, core/data/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/data/repository/CommunityRepository.kt, core/data/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/data/repository/SettingThemeRepository.kt, core/data/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/data/repository/di/SettingThemeModule.kt, core/model/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/model/setting/SettingTheme.kt, feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/home/DiaryHomeScreen.kt, feature/setting/src/main/java/com/boostcamp/dreamteam/dreamdiary/setting/SettingNavigation.kt, feature/setting/src/main/java/com/boostcamp/dreamteam/dreamdiary/setting/SettingScreen.kt, feature/setting/src/main/java/com/boostcamp/dreamteam/dreamdiary/setting/theme/SettingThemeScreen.kt, feature/setting/src/main/java/com/boostcamp/dreamteam/dreamdiary/setting/theme/SettingThemeViewModel.kt, feature/setting/src/main/res/values/strings.xml, gradle/libs.versions.toml
설정에 "다크모드 설정"을 "테마 설정"으로 변경하고, 누르면 테마 설정 화면으로 넘어가 시스템, 라이트, 다크 중 하나를 선택할 수 있습니다.
nia를 참고하여 `setKeepOnScreenCondition` 호출이나 `enableEdgeToEdge`를 재차 호출하는 코드를 작성했습니다.
`setKeepOnScreenCondition`는 테마 설정을 읽어 들일 때까지 스플래시 화면을 계속 띄워주는데 사용합니다. 이걸 안하면 설정을 읽기 전 시스템 테마를 따라갔다가 설정을 다 읽은 후 해당 설정으로 바뀌어, 시스템 테마가 라이트이고 앱 테마를 다크로 해두었을 경우 라이트 -> 다크로 넘어가는 깜빡임이 보입니다.
`enableEdgeToEdge`를 재차 호출하는 부분은, 상태 바나 네비게이션 바가 시스템의 테마를 따라가는 걸 방지하는 용도로 보입니다. 이걸 안하면 시스템 테마가 라이트인데 앱 테마를 다크로 해두었을 때, 앱 화면은 다크인데 네비게이션은 하얗습니다.
=> [feat] 테마 색상 변경

feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/home/component/DiaryCalendarBottomSheet.kt
closes #263 
가로 길이가 짧아서 보이는 영역이 짧았던 것 같습니다.
=> [fix] 달력 bottomSheet listItem 가로 크기 늘리기

feature/community/src/main/java/com/boostcamp/dreamteam/dreamdiary/community/write/CommunityWriteScreen.kt, feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/write/DiaryWriteScreen.kt
#258 
`takePersistableUriPermission`를 실패하는 기종이 있는 것 같습니다. `SecurityException`를 내뿜는데, 이를 무시하도록 했습니다.
해당 함수는 이 uri를, 앱을 껐다 켰을 때에도 접근 권한을 가지게 하는 함수로 알고 있습니다. 반대로 이 함수를 호출하지 않으면 임시적인 권한이므로 항상 호출하게 해 두었는데, 사실 우리 앱에서는 화면이 있을 때 이미지를 업로드하므로 임시적인 권한으로도 모두 처리가 가능할 것으로 생각됩니다.
실제로 이 함수 호출이 실패했을 때에는, cache 폴더 등에 복사해서 그 파일을 이용하는게 가장 완벽한 해결법인 것 같습니다.
=> [fix] takePersistableUriPermission의 익셉션 처리

.gitignore, app/src/main/res/values/strings.xml, build-logic/convention/src/main/java/com/boostcamp/dreamteam/dreamdiary/buildlogic/convention/AndroidApplicationConventionPlugin.kt, core/data/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/data/repository/CommentRepository.kt, feature/community/src/main/java/com/boostcamp/dreamteam/dreamdiary/community/list/CommunityListScreen.kt
=> [feat] 0.0.4 버전 배포
