app/build.gradle.kts
build.gradle.kts
gradle/libs.versions.toml

Closes #29 
hilt-navigation-compose를 추가

chore: hilt-navigation-compose 추가

---

core/model/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/model/Diary.kt
core/model/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/model/Label.kt
feature/diary/build.gradle.kts
feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/DiaryHomeScreen.kt
feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/DiaryListScreen.kt
feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/components/DiaryCard.kt
feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/components/DiaryListTab.kt
gradle/libs.versions.toml

- close: #10, #11 
- [feat] 나의 일기 목록(리스트) 화면 구현

[feat] 나의 일기 목록(리스트) 화면 구현

---

build-logic/gradle.properties
gradle.properties

close #38 
- parallel을 사용하도록 설정
- caching을 사용하도록 설정

[chore] 빌드 속도 향상

---

app/src/main/AndroidManifest.xml
app/src/main/java/com/boostcamp/dreamteam/dreamdiary/DreamDiaryApplication.kt
app/src/main/java/com/boostcamp/dreamteam/dreamdiary/MainActivity.kt

closes: #42
- hilt application 추가

[feat] hilt application 추가

---

.editorconfig

```kotlin
@HiltViewModel
class DiaryViewModel
@Inject
constructor(
getDiariesUseCase: GetDiariesUseCase,
) : ViewModel() {
}
```
이렇게 포멧팅 되는 것은 아무리 생각해도 좀 아닌 것 같습니다;

[chore] 어노테이션 관련 lint 규칙 수정

---

feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/write/DiaryWriteScreen.kt
feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/write/DiaryWriteViewModel.kt
feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/write/model/DiaryWriteUiState.kt

closes: #48
- diary write viewmodel 생성

[feat] diary write viewmodel 생성

---

app/src/main/java/com/boostcamp/dreamteam/dreamdiary/navigation/DreamDiaryNavHost.kt
feature/diary/build.gradle.kts
feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/home/DiaryHomeNavigatioin.kt
feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/home/DiaryHomeScreen.kt
feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/home/components/DiaryCalendarTab.kt
feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/home/components/DiaryCard.kt
feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/home/components/DiaryListTab.kt

[feat] home navigation 연결

---

feature/diary/build.gradle.kts
feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/home/DiaryHomeScreen.kt
feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/home/components/DiaryCard.kt
feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/home/components/DiaryListTab.kt

[feat] preview에 테마 적용

---

feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/DiaryHomeUIState.kt
feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/home/DiaryHomeScreen.kt
feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/home/DiaryHomeUIState.kt
feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/home/DiaryHomeViewModel.kt
feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/home/DiaryViewModel.kt

[refactor] home 잘못된 패키지 이동

---

app/src/main/java/com/boostcamp/dreamteam/dreamdiary/navigation/DreamDiaryNavHost.kt
feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/write/DiaryWriteNavigation.kt
feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/write/DiaryWriteScreen.kt
feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/write/DiaryWriteViewModel.kt
feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/write/model/DiaryWriteEvent.kt

#24 
제목과 내용(문자열만) 데이터를 가지는 꿈일기를 작성할 수 있습니다

[feat] 꿈일기 작성 기능

---

feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/write/DiaryWriteScreen.kt
feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/write/DiaryWriteViewModel.kt
feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/write/components/LabelItem.kt
feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/write/components/LabelSelectionDialog.kt
feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/write/model/DiaryWriteUiState.kt

close #51
- 라벨 아이콘 클릭시 카테고리 선택할 수 있는 다이이얼로그 나오도록 구현
- ui는 사람들 피드백 받고서 수정여부 결정

[feat] label selection UI

---

app/build.gradle.kts
app/src/main/java/com/boostcamp/dreamteam/dreamdiary/DreamDiaryApplication.kt
build-logic/convention/src/main/java/com/boostcamp/dreamteam/dreamdiary/buildlogic/convention/AndroidLibraryConventionPlugin.kt
core/data/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/data/database/FirebaseDataSource.kt
feature/diary/build.gradle.kts
feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/write/DiaryWriteViewModel.kt
gradle/libs.versions.toml

close #91 
```
TB(FirebaseDataSource.kt:21)#invoke         // {팀버}({파일명})#{함수이름}
com.boostcamp.dreamteam.dreamdiary    // 패키지 명
D  																// 로깅 레벨(D: debug)
1 => {createdAt=2021-09-01, images=[], id=1, title=오늘의 일기, content=오늘은 날씨가 좋았다., labels=[{name=기쁨}, {name=행복}, {name=환희}], updatedAt=2021-09-01}
```
로그의 파일 이름 부분을 클릭하면  
해당 파일로 쉽게 이동 가능합니다.
또한 어떤 함수에서 로깅을 시도했는지(이미지의 경우 invoke)도 보여줍니다.

[chore] timber 라이브러리 추가

---

.github/workflows/lint_and_build.yml

- gradlew를 사용하는 것이 아닌 action을 직접 사용

[chore] ktlint 속도를 더 빠르게 하기 위해 외부에서 확인

---

README.md

[docs] update readme.md

---

feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/home/tabcalendar/DiaryHomeTabCalendarUIState.kt

[feat] uistate 클래스 생성

---

core/designsystem/src/main/java/com/boostcamp/dreamteam/dreamdiary/designsystem/theme/Theme.kt

[fix] dynamic color를 사용하지 않도록 변경

---

feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/home/DiaryHomeScreen.kt
feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/home/DiaryHomeViewModel.kt
feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/home/tabcalendar/DiaryCalendarTab.kt

[feat] uistate 연결

---

core/data/schema/com.boostcamp.dreamteam.dreamdiary.core.data.database.DreamDiaryDatabase/1.json
core/data/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/data/database/dao/DreamDiaryDao.kt
core/data/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/data/database/model/DreamDiaryEntity.kt
core/data/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/data/repository/DefaultDreamDiaryRepository.kt
core/data/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/data/repository/DreamDiaryRepository.kt
core/domain/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/domain/usecase/AddDreamDiaryUseCase.kt
feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/write/DiaryWriteScreen.kt
feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/write/DiaryWriteViewModel.kt
feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/write/component/DiaryWriteScreenBody.kt
feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/write/component/DiaryWriteScreenHeader.kt
feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/write/component/WriteDateInfo.kt
feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/write/model/DiaryWriteUiState.kt
feature/diary/src/main/res/values/strings.xml

close #73 
꿈일기를 저장할 때 시간을 설정할 수 있는 UI
데이터베이스에 잠 든 시간 및 잠 깬 시간 정보를 저장할 수 있는 필드 추가

[feat] 꿈일기를 저장할 때 시간을 함께 저장할 수 있는 기능

---

README.md

[docs] README.md 잘못된 년도 수정

---

feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/home/component/DiaryCalendar.kt
feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/home/component/DiaryCalendarBody.kt
feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/model/DiaryUi.kt

[feat] 달력에 일기 작성 날짜 표시 추가

---

core/model/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/model/Diary.kt
feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/model/DiaryUi.kt

[fix] Diary model 수정

---

feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/home/component/DiaryCalendarBody.kt
feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/model/DiaryUi.kt

- 기준에 해당하는 필드를 사용하여, 정렬 혹은 필터링 시 해당 기준을 사용하도록 변경

[feat] 기준에 해당하는 필드 값 추가

---

core/data/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/data/database/dao/DreamDiaryDao.kt
core/data/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/data/repository/DefaultDreamDiaryRepository.kt
core/data/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/data/repository/DreamDiaryRepository.kt
core/data/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/data/repository/Mapper.kt
core/domain/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/domain/usecase/GetDreamDiariesInRangeByUseCase.kt
core/model/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/model/Diary.kt
core/model/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/model/Label.kt
feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/home/DiaryHomeViewModel.kt
feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/model/DiaryUi.kt

[feat] 달력에 저장된 일기 표시

---

feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/home/component/DiaryCalendarBottomSheet.kt
feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/home/tabcalendar/DiaryCalendarTab.kt

현재 선택 중인 날짜를 BottomSheetHeader까지 땡겨서 포매팅 적용 후 출력했습니다.

[feat] 꿈일기 바텀시트에 현재 선택 중인 날짜를 표시

---

app/src/main/res/values/strings.xml
core/ui/src/main/res/values/strings.xml
feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/home/DiaryHomeScreen.kt
feature/diary/src/main/res/values/strings.xml

- topbar, bottom navigation 제목 변경
- 나의 일기 -> 나의 꿈

[fix] topbar, bottom navigation 제목 변경

---

feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/home/DiaryHomeScreen.kt
feature/diary/src/main/res/values/strings.xml

- menu 삭제
- scaffold preview 볼 수 있도록 수정

[fix] topbar ui 수정

---

.github/workflows/build.yml
.github/workflows/ktlin_check.yml

- 작업 병렬로 하도록 분리
- no daemon 적용

[feat] ktlint, build 작업 분리

---

feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/home/DiaryHomeScreen.kt
feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/home/component/DiaryCard.kt
feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/home/tablist/DiaryListTab.kt
feature/diary/src/main/res/values/strings.xml

[feat] card에 메뉴 버튼 추가

---

app/build.gradle.kts
core/data/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/data/repository/AuthRepository.kt
feature/auth/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/auth/SignInScreen.kt
feature/auth/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/auth/SignInViewModel.kt
feature/setting/src/main/java/com/boostcamp/dreamteam/dreamdiary/setting/SettingScreen.kt
feature/setting/src/main/java/com/boostcamp/dreamteam/dreamdiary/setting/SettingViewModel.kt
feature/setting/src/main/res/values/strings.xml

[feat] 로그아웃 구현

---

core/data/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/data/repository/AuthRepository.kt
feature/setting/src/main/java/com/boostcamp/dreamteam/dreamdiary/setting/SettingScreen.kt
feature/setting/src/main/java/com/boostcamp/dreamteam/dreamdiary/setting/SettingViewModel.kt

close #84 
- 파이어베이스에 로그인된 provider및 이메일 다이얼로그 생성

[feat] SNS 계정 확인

---

app/build.gradle.kts
app/src/main/AndroidManifest.xml
feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/home/DiaryHomeNavigatioin.kt
feature/widget/src/main/AndroidManifest.xml
feature/widget/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/widget/DiaryWriteAction.kt
feature/widget/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/widget/DiaryWriteWidget.kt
feature/widget/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/widget/WidgetReceiver.kt
feature/widget/src/main/res/drawable/ic_android.xml
feature/widget/src/main/res/values/strings.xml
feature/widget/src/main/res/xml-v31/diary_write_appwidget_info.xml
feature/widget/src/main/res/xml/diary_write_appwidget_info.xml

[feat] diary write widget 구현

---

core/designsystem/src/main/java/com/boostcamp/dreamteam/dreamdiary/designsystem/component/Card.kt
feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/home/component/DiaryCard.kt
feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/model/DiaryUi.kt

[feat] 재활용하기 위한 카드 구현

---

core/data/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/data/database/dao/DreamDiaryDao.kt
core/data/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/data/repository/DefaultDreamDiaryRepository.kt
core/data/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/data/repository/DreamDiaryRepository.kt
core/domain/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/domain/usecase/GetDreamDiariesByFilterUseCase.kt
feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/home/DiaryHomeScreen.kt
feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/home/DiaryHomeViewModel.kt
feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/home/tablist/DiaryListTab.kt
feature/diary/src/main/res/values/strings.xml

Co-authored-by: ruh0n <wns8256@naver.com>
close #149 
라벨 필터링 칩 만듬

[feat] 홈 다이어리 라벨 필터UI

---

feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/write/DiaryWriteViewModel.kt
feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/write/component/LabelItem.kt
feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/write/component/LabelSelectionDialog.kt

[fix] dialog 높이 고정

---

feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/home/DiaryHomeNavigatioin.kt
feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/home/DiaryHomeScreen.kt
feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/home/component/DiaryCard.kt
feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/home/tablist/DiaryListTab.kt
feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/write/DiaryWriteViewModel.kt
feature/diary/src/main/res/values/strings.xml

Added diary editing functionality to the home screen:

[feat] 일기 편집 네비게이션 연결

---

feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/write/DiaryWriteViewModel.kt
feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/write/model/DiaryWriteUiState.kt

[feat] write 화면의 초기 데이터 구성

---

core/data/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/data/database/dao/DreamDiaryDao.kt
core/data/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/data/repository/DefaultDreamDiaryRepository.kt
core/data/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/data/repository/DreamDiaryRepository.kt
core/domain/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/domain/usecase/UpdateDreamDiaryWithContentsUseCase.kt
feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/write/DiaryWriteScreen.kt
feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/write/DiaryWriteViewModel.kt
feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/write/model/DiaryWriteEvent.kt
feature/diary/src/main/res/values/strings.xml

[feat] 일기 수정 기능 구현

---

feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/detail/DiaryDetailScreen.kt
feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/detail/model/DiaryDetailUiState.kt
feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/home/DiaryHomeNavigatioin.kt

[feat] 일기 상세화면에 수정/삭제 메뉴 추가

---

core/data/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/data/repository/DefaultDreamDiaryRepository.kt

[fix] 라벨이 수정되지 않는 문제 해결

---

core/data/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/data/database/dao/DreamDiaryDao.kt
core/data/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/data/repository/DefaultDreamDiaryRepository.kt
core/data/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/data/repository/DreamDiaryRepository.kt
core/domain/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/domain/usecase/AddDreamDiaryWithContentsUseCase.kt
feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/home/DiaryHomeNavigatioin.kt
feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/write/DiaryWriteScreen.kt
feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/write/DiaryWriteViewModel.kt
feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/write/model/DiaryWriteEvent.kt

[feat] 일기 작성 및 수정 후 상세화면 자동 이동

---

core/data/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/data/database/dao/DreamDiaryDao.kt
core/data/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/data/repository/DefaultDreamDiaryRepository.kt
core/data/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/data/repository/DreamDiaryRepository.kt
core/domain/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/domain/usecase/DeleteDreamDiariesUseCase.kt
feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/home/DiaryHomeScreen.kt
feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/home/DiaryHomeViewModel.kt
feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/home/tablist/DiaryListTab.kt

[feat] 홈 화면 일기 삭제

---

feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/detail/DiaryDetailScreen.kt
feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/detail/DiaryDetailViewModel.kt
feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/detail/model/DiaryDetailEvent.kt

[feat] 상세화면 - 일기 삭제 기능 구현

---

core/data/schema/com.boostcamp.dreamteam.dreamdiary.core.data.database.DreamDiaryDatabase/1.json
core/data/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/data/database/dao/DreamDiaryDao.kt
core/data/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/data/database/model/DreamDiaryEntity.kt
core/data/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/data/repository/DefaultDreamDiaryRepository.kt

[feat] 일기 삭제 정책을 soft delete로 변경

---

feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/home/tablist/DiaryListTab.kt
feature/diary/src/main/res/values/strings.xml

[feat] 비어있는 리스트 화면 꾸미기

---

core/designsystem/src/main/java/com/boostcamp/dreamteam/dreamdiary/designsystem/component/Card.kt

[fix] tail에 내용물이 있을 때에만 spacer 표시

---

feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/home/tablist/DiaryListTab.kt

[hotfix] 잘못 설정된 key 수정

---

core/ui/src/main/java/com/boostcamp/dreamteam/dreamdiary/ui/HomeBottomNavItem.kt
core/ui/src/main/java/com/boostcamp/dreamteam/dreamdiary/ui/HomeBottomNavigation.kt
feature/community/src/main/java/com/boostcamp/dreamteam/dreamdiary/community/CommunityScreen.kt
feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/home/DiaryHomeScreen.kt
feature/setting/src/main/java/com/boostcamp/dreamteam/dreamdiary/setting/SettingScreen.kt

[feat] bottom navigation 선택된 아이콘 색칠하기

---

app/src/main/java/com/boostcamp/dreamteam/dreamdiary/navigation/DreamDiaryNavHost.kt
feature/community/src/main/java/com/boostcamp/dreamteam/dreamdiary/community/CommunityListScreen.kt
feature/community/src/main/java/com/boostcamp/dreamteam/dreamdiary/community/CommunityNavigation.kt
feature/community/src/main/java/com/boostcamp/dreamteam/dreamdiary/community/CommunityScreen.kt
feature/community/src/main/java/com/boostcamp/dreamteam/dreamdiary/community/list/CommunityListScreen.kt
feature/community/src/main/java/com/boostcamp/dreamteam/dreamdiary/community/list/CommunityListUiState.kt
feature/community/src/main/java/com/boostcamp/dreamteam/dreamdiary/community/list/CommunityListViewModel.kt
feature/community/src/main/java/com/boostcamp/dreamteam/dreamdiary/community/model/DiaryUi.kt

[feat] 비어있는 CommunityListScreen 생성

---

feature/community/src/main/java/com/boostcamp/dreamteam/dreamdiary/community/CommunityNavigation.kt
feature/community/src/main/java/com/boostcamp/dreamteam/dreamdiary/community/list/CommunityListScreen.kt

[fix] community navigation 캡슐화

---

feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/home/DiaryHomeScreen.kt
feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/home/DiaryHomeViewModel.kt
feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/home/tablist/DiaryHomeTabListUIState.kt
feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/home/tablist/DiaryListTab.kt
feature/diary/src/main/res/values/strings.xml

[feat] 꿈 일기 정렬 버튼 추가

---

feature/setting/src/main/java/com/boostcamp/dreamteam/dreamdiary/setting/SettingNavigation.kt
feature/setting/src/main/java/com/boostcamp/dreamteam/dreamdiary/setting/component/SettingOption.kt

- switch ui
- settingOption으로 switch ui 여부

[feat] setting option switch ui

---

feature/community/src/main/java/com/boostcamp/dreamteam/dreamdiary/community/list/component/CommunityDiaryCard.kt
feature/community/src/main/java/com/boostcamp/dreamteam/dreamdiary/community/model/vo/DisplayableDateTime.kt
feature/community/src/main/java/com/boostcamp/dreamteam/dreamdiary/community/model/vo/DisplayableDateTimeFormatter.kt

[fix] community 피드백 반영

---

app/src/main/java/com/boostcamp/dreamteam/dreamdiary/navigation/DreamDiaryNavHost.kt
feature/setting/src/main/java/com/boostcamp/dreamteam/dreamdiary/setting/SettingNavigation.kt
feature/setting/src/main/java/com/boostcamp/dreamteam/dreamdiary/setting/SettingScreen.kt
feature/setting/src/main/java/com/boostcamp/dreamteam/dreamdiary/setting/component/SettingOption.kt

#179 에서 작업한 ui navigation 연결했습니다.

[feat] setting backup screen navigation 연결

---

core/notification/src/main/java/com/boostcamp/dreamteam/dreamdiary/notification/ScreenOffTimeTracker.kt
feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/home/DiaryHomeNavigatioin.kt
feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/write/DiaryWriteViewModel.kt
feature/setting/src/main/java/com/boostcamp/dreamteam/dreamdiary/setting/SettingScreen.kt

[feat] 알람누르면 잔시간 가지고 작성페이지로

---

feature/community/src/main/java/com/boostcamp/dreamteam/dreamdiary/community/write/CommunityWriteScreen.kt
feature/community/src/main/java/com/boostcamp/dreamteam/dreamdiary/community/write/component/CommunityEditor.kt

[fix] 커뮤니티 작성 화면 버그 수정

---

feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/home/DiaryHomeScreen.kt

- 홈 화면 스크롤 시 topappbar 숨기기
탭도 숨기고싶은데 어렵네요

[feat] 홈 화면 스크롤 시 topappbar 숨기기

---

feature/community/src/main/java/com/boostcamp/dreamteam/dreamdiary/community/write/CommunityWriteScreen.kt
feature/community/src/main/java/com/boostcamp/dreamteam/dreamdiary/community/write/component/CommunityEditor.kt
feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/write/DiaryWriteScreen.kt

[feat] padding 수정, placeholder 숨기기

---

app/build.gradle.kts
build.gradle.kts
gradle/libs.versions.toml

[feat] firebase creashlytics 추가

---

feature/community/src/main/java/com/boostcamp/dreamteam/dreamdiary/community/list/CommunityListScreen.kt
feature/community/src/main/java/com/boostcamp/dreamteam/dreamdiary/community/list/CommunityListViewModel.kt

[feat] 커뮤니티 당겨서 새로고침 로직 추가

---

feature/community/src/main/java/com/boostcamp/dreamteam/dreamdiary/community/detail/CommunityDetailEvent.kt
feature/community/src/main/java/com/boostcamp/dreamteam/dreamdiary/community/detail/CommunityDetailScreen.kt
feature/community/src/main/java/com/boostcamp/dreamteam/dreamdiary/community/detail/CommunityDetailUiState.kt
feature/community/src/main/java/com/boostcamp/dreamteam/dreamdiary/community/detail/CommunityDetailViewModel.kt

closes #193
- comment add하면 refresh 로직

[feat] comment add

---

feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/home/tablist/DiaryListTab.kt

첫 로딩 중에는 아무것도 보여주지 않도록 변경, 
room이라 빨라서 shimmer도 없는 게 나을 듯

[feat] 홈 화면 로딩 중에는 아무것도 보여주지 않도록 변경

---

feature/community/src/main/java/com/boostcamp/dreamteam/dreamdiary/community/list/CommunityListScreen.kt
feature/community/src/main/java/com/boostcamp/dreamteam/dreamdiary/community/list/component/CommunityDiaryCard.kt

- 스크롤 방지
- 아이콘 버튼 터치 방지
- dialog 눈에 잘 띄도록 변경

[fix] 커뮤니티 목록 로그인 하지 않을 경우 스크롤 방지 

---

feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/component/DiaryInfosEditor.kt
feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/component/component/LabelItem.kt
feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/component/component/LabelSelectionDialog.kt
feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/detail/DiaryDetailScreen.kt
feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/write/DiaryWriteScreen.kt
feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/write/DiaryWriteViewModel.kt
feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/write/model/DiaryWriteEvent.kt

[feat] 라벨 수정 기능 제거

---

feature/community/src/main/java/com/boostcamp/dreamteam/dreamdiary/community/CommunityNavigation.kt
feature/community/src/main/java/com/boostcamp/dreamteam/dreamdiary/community/write/CommunityWriteEvent.kt
feature/community/src/main/java/com/boostcamp/dreamteam/dreamdiary/community/write/CommunityWriteScreen.kt
feature/community/src/main/java/com/boostcamp/dreamteam/dreamdiary/community/write/CommunityWriteScreenState.kt
feature/community/src/main/java/com/boostcamp/dreamteam/dreamdiary/community/write/CommunityWriteViewModel.kt
feature/community/src/main/res/values/strings.xml

[feat] 공유 성공 후 바로 상세 화면으로 이동

---

core/data/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/data/repository/CommunityRepository.kt
core/domain/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/domain/usecase/community/GetCommunityPostsUseCase.kt
core/model/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/model/community/CommunityPostList.kt
core/ui/src/main/java/com/boostcamp/dreamteam/dreamdiary/ui/util/FlowExtension.kt
feature/community/src/main/java/com/boostcamp/dreamteam/dreamdiary/community/CommunityNavigation.kt
feature/community/src/main/java/com/boostcamp/dreamteam/dreamdiary/community/detail/CommunityDetailScreen.kt
feature/community/src/main/java/com/boostcamp/dreamteam/dreamdiary/community/detail/CommunityDetailViewModel.kt
feature/community/src/main/java/com/boostcamp/dreamteam/dreamdiary/community/detail/component/CommunityDetailComment.kt
feature/community/src/main/java/com/boostcamp/dreamteam/dreamdiary/community/list/CommunityListEvent.kt
feature/community/src/main/java/com/boostcamp/dreamteam/dreamdiary/community/list/CommunityListScreen.kt
feature/community/src/main/java/com/boostcamp/dreamteam/dreamdiary/community/list/CommunityListUiState.kt
feature/community/src/main/java/com/boostcamp/dreamteam/dreamdiary/community/list/CommunityListViewModel.kt
feature/community/src/main/java/com/boostcamp/dreamteam/dreamdiary/community/list/component/CommunityDiaryCard.kt
feature/community/src/main/java/com/boostcamp/dreamteam/dreamdiary/community/model/PostUi.kt
feature/community/src/main/java/com/boostcamp/dreamteam/dreamdiary/community/write/CommunityWriteEvent.kt
feature/community/src/main/java/com/boostcamp/dreamteam/dreamdiary/community/write/CommunityWriteScreen.kt
feature/community/src/main/java/com/boostcamp/dreamteam/dreamdiary/community/write/CommunityWriteScreenState.kt
feature/community/src/main/java/com/boostcamp/dreamteam/dreamdiary/community/write/CommunityWriteViewModel.kt
feature/community/src/main/res/values/strings.xml
feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/component/DiaryInfosEditor.kt
feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/component/component/LabelItem.kt
feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/component/component/LabelSelectionDialog.kt
feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/detail/DiaryDetailScreen.kt
feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/home/tablist/DiaryListTab.kt
feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/write/DiaryWriteScreen.kt
feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/write/DiaryWriteViewModel.kt
feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/write/model/DiaryWriteEvent.kt

- 리스트 화면 좋아요
- 네트워크 연결 유무 상관없이 바로 반영되도록 구현
- 실패하면 Toast메시지

[feat] community list 화면 좋아요

---

feature/community/src/main/java/com/boostcamp/dreamteam/dreamdiary/community/list/CommunityListScreen.kt
feature/community/src/main/java/com/boostcamp/dreamteam/dreamdiary/community/list/component/CommunityDiaryCard.kt

[feat] 커뮤니티 post 카드 정상화

---

core/synchronization/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/synchronization/SyncWorkState.kt
core/synchronization/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/synchronization/SynchronizationWorker.kt
feature/diary/build.gradle.kts
feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/home/DiaryHomeScreen.kt
feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/home/model/SyncStateUi.kt

홈화면(리스트)에서 종 아이콘 없에고 동기화 버튼 넣었습니다.
getWorkInfosForUniqueWorkFlow 함수로 워커의 상태를 받아오게 했습니다.
동기화 중이거나 아닌 상태에 맞추어 버튼이 돌아가는 애니메이션을 추가했습니다.

[feat] 동기화 버튼 추가

---

core/ui/src/main/java/com/boostcamp/dreamteam/dreamdiary/ui/HomeBottomNavigation.kt
feature/community/src/main/java/com/boostcamp/dreamteam/dreamdiary/community/list/CommunityListScreen.kt
feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/home/DiaryHomeScreen.kt
feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/home/tablist/DiaryListTab.kt

지학님이 힘을 숨기시는 것 처럼  
스크롤중에 bottom navigation bar를 숨기기로 하였습니다.
home, community 둘 다 숨겨집니다.
그런데 시스템바 뒤에 비치네요

[feat] 스크롤시 bottombar를 숨김

---

core/data/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/data/database/dao/DreamDiaryDao.kt
core/data/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/data/repository/DefaultDreamDiaryRepository.kt
core/data/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/data/repository/DreamDiaryRepository.kt
core/domain/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/domain/usecase/GetDreamDiariesByTitleUseCase.kt
core/domain/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/domain/usecase/GetSearchSuggestions.kt
feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/home/DiaryHomeNavigatioin.kt
feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/home/DiaryHomeScreen.kt
feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/home/component/DiaryCard.kt
feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/search/DiarySearchScreen.kt
feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/search/DiarySearchUiState.kt
feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/search/DiarySearchViewModel.kt
feature/diary/src/main/res/values/strings.xml

- 검색 화면 추가
- 검색어 추천 추가
- 검색 결과 확인

[feat] 검색 추가

---

README.md

[docs] readme 업데이트

---

core/data/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/data/dto/CommentRequest.kt
core/data/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/data/dto/CommentResponse.kt
core/data/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/data/repository/CommunityRepository.kt
core/model/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/model/Comment.kt
feature/community/src/main/java/com/boostcamp/dreamteam/dreamdiary/community/detail/component/CommunityDetailPostCard.kt
feature/community/src/main/java/com/boostcamp/dreamteam/dreamdiary/community/list/CommunityListScreen.kt
feature/community/src/main/java/com/boostcamp/dreamteam/dreamdiary/community/list/CommunityListViewModel.kt
feature/community/src/main/java/com/boostcamp/dreamteam/dreamdiary/community/list/component/CommunityDiaryCard.kt
feature/community/src/main/java/com/boostcamp/dreamteam/dreamdiary/community/model/PostDetailUi.kt
feature/community/src/main/java/com/boostcamp/dreamteam/dreamdiary/community/model/PostUi.kt

[feat] 좋아요 수 표시

---

core/data/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/data/database/dao/DreamDiaryDao.kt
core/data/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/data/repository/CommunityRepository.kt
core/data/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/data/repository/DefaultDreamDiaryRepository.kt
core/data/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/data/repository/DreamDiaryRepository.kt
core/domain/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/domain/usecase/DeleteLabelUseCase.kt
feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/component/component/LabelItem.kt
feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/component/component/LabelSelectionDialog.kt
feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/write/DiaryWriteViewModel.kt
feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/write/model/DiaryWriteEvent.kt
feature/diary/src/main/res/values/strings.xml

[feat] label 삭제 기능 추가

---

README.md
build-logic/convention/src/main/java/com/boostcamp/dreamteam/dreamdiary/buildlogic/convention/AndroidApplicationConventionPlugin.kt

0.0.2 버전 배포

---

README.md

[feat] 리드미 수정

---

feature/setting/src/main/java/com/boostcamp/dreamteam/dreamdiary/setting/SettingScreen.kt
feature/setting/src/main/res/values/strings.xml

[feat] 로그아웃 다이얼로그

---

feature/community/src/main/java/com/boostcamp/dreamteam/dreamdiary/community/list/component/CommunityDiaryCard.kt

[fix] 커뮤니티 카드모양에 맞춘 클릭 영역

---

feature/setting/src/main/java/com/boostcamp/dreamteam/dreamdiary/setting/SettingScreen.kt

[fix] 셋팅 아래 8패딩 서순 변경

---

feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/write/DiaryWriteScreen.kt
feature/diary/src/main/res/values/strings.xml

#266 
성공 이벤트들은 toast를 안 보여주는 것이 더 좋을 것 같아요~

[fix] 일기 작성 성공 toast 제거

---

feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/home/DiaryHomeScreen.kt

closes #279 
가로 스와이프를 통해 탭 전환이 가능해졌습니다.

[feat] 가로 스크롤로 탭 전환 가능

---

core/designsystem/build.gradle.kts
core/designsystem/src/main/java/com/boostcamp/dreamteam/dreamdiary/designsystem/component/Card.kt
feature/community/src/main/java/com/boostcamp/dreamteam/dreamdiary/community/list/CommunityListScreen.kt
gradle/libs.versions.toml

[chore] 커뮤니티 로딩중 shimmer 효과 추가

---

feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/component/DiaryMenuButton.kt
feature/diary/src/main/res/values/strings.xml

close #255
- content description 추가
- icon 변경
아이콘 변경

[fix] 공유 -> 게시 이름 변경

---

feature/setting/src/main/java/com/boostcamp/dreamteam/dreamdiary/setting/component/SettingOption.kt

[feat] 설정화면의 미구현 기능은 toast 메시지를 띄우는 것으로 변경

---

feature/community/src/main/java/com/boostcamp/dreamteam/dreamdiary/community/write/CommunityWriteScreen.kt
feature/community/src/main/res/values/strings.xml
feature/diary/src/main/java/com/boostcamp/dreamteam/dreamdiary/feature/diary/write/DiaryWriteScreen.kt
feature/diary/src/main/res/values/strings.xml

[fix] 제목과 컨텐트가 없을 때 작성x로 수정

---

feature/community/src/main/java/com/boostcamp/dreamteam/dreamdiary/community/detail/component/CommunityDetailPostCard.kt

[feat] community detail 날짜 추가

---

core/data/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/data/repository/AuthRepository.kt
core/data/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/data/repository/CommentRepository.kt
core/domain/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/domain/usecase/community/DeleteCommentUseCase.kt
feature/community/src/main/java/com/boostcamp/dreamteam/dreamdiary/community/detail/CommunityDetailEvent.kt
feature/community/src/main/java/com/boostcamp/dreamteam/dreamdiary/community/detail/CommunityDetailScreen.kt
feature/community/src/main/java/com/boostcamp/dreamteam/dreamdiary/community/detail/CommunityDetailViewModel.kt
feature/community/src/main/java/com/boostcamp/dreamteam/dreamdiary/community/detail/component/CommunityCommentsMenuButton.kt
feature/community/src/main/java/com/boostcamp/dreamteam/dreamdiary/community/detail/component/CommunityDetailComment.kt
feature/community/src/main/java/com/boostcamp/dreamteam/dreamdiary/community/model/CommentUi.kt
feature/community/src/main/res/values/strings.xml

[feat] 댓글 삭제 기능

---

core/data/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/data/firebase/FirebaseCommunityPostPagingSource.kt
core/data/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/data/firebase/firestore/model/FirestoreAddCommunityPostRequest.kt
core/data/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/data/repository/CommunityRepository.kt
core/domain/src/main/java/com/boostcamp/dreamteam/dreamdiary/core/domain/usecase/community/DeleteCommunityPostUseCase.kt
feature/community/src/main/java/com/boostcamp/dreamteam/dreamdiary/community/CommunityNavigation.kt
feature/community/src/main/java/com/boostcamp/dreamteam/dreamdiary/community/detail/CommunityDetailEvent.kt
feature/community/src/main/java/com/boostcamp/dreamteam/dreamdiary/community/detail/CommunityDetailScreen.kt
feature/community/src/main/java/com/boostcamp/dreamteam/dreamdiary/community/detail/CommunityDetailViewModel.kt
feature/community/src/main/java/com/boostcamp/dreamteam/dreamdiary/community/detail/component/CommunityDetailMenuButton.kt
feature/community/src/main/java/com/boostcamp/dreamteam/dreamdiary/community/list/CommunityListScreen.kt
feature/community/src/main/java/com/boostcamp/dreamteam/dreamdiary/community/list/CommunityListViewModel.kt
feature/community/src/main/java/com/boostcamp/dreamteam/dreamdiary/community/model/PostDetailUi.kt
feature/community/src/main/res/values/strings.xml

[feat] 삭제 기능을 구현
